
// Create Items
StartupEvents.registry('item', event => {

    event.create("tooltip_color_palette")
        .displayName("Tooltip Color Palette")
        .tooltip(Text.of("§0 | Black"))
        .tooltip(Text.of("§1 | Dark Blue"))
        .tooltip(Text.of("§2 | Dark Green"))
        .tooltip(Text.of("§3 | Dark Aqua"))
        .tooltip(Text.of("§4 | Dark Red"))
        .tooltip(Text.of("§5 | Dark Purple"))
        .tooltip(Text.of("§6 | Gold"))
        .tooltip(Text.of("§7 | Gray"))
        .tooltip(Text.of("§8 | Dark Gray"))
        .tooltip(Text.of("§9 | Blue"))
        .tooltip(Text.of("§a | Green"))
        .tooltip(Text.of("§b | Aqua"))
        .tooltip(Text.of("§c | Red"))
        .tooltip(Text.of("§d | Light Purple"))
        .tooltip(Text.of("§e | Yellow"))
        .tooltip(Text.of("§f | White"))


    //////////////////////
    /// Dermal Plating ///
    //////////////////////

    event.create("dermal_plating_gold")
        .displayName("§8Gold Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +3 Armor"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 1 Dermal Plating"))

    event.create("dermal_plating_iron")
        .displayName("§8Iron Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +4 Armor"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 2 Dermal Plating"))

    event.create("dermal_plating_diamond")
        .displayName("§bDiamond Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +5 Armor"))
        .tooltip(Text.of("§7 Gives +2 Armor Toughness"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 3 Dermal Plating"))

    event.create("dermal_plating_netherite")
        .displayName("§dNetherite Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +5 Armor"))
        .tooltip(Text.of("§7 Gives +3 Armor Toughness"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 4 Dermal Plating"))

    ///////////////////////
    /// Source Circuits ///
    ///////////////////////
    
    event.create("source_circuits_tier_1")
        .displayName("§8Starter Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Novice Source Circuits"))
        .tooltip(Text.of("§b - Apprentice Source Circuits"))
        .tooltip(Text.of("§b - Mage Source Circuits"))
        .tooltip(Text.of("§b - Master Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 1 Source Circuits"))
    
    event.create("source_circuits_tier_2")
        .displayName("§7Novice Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 10"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Circuits"))
        .tooltip(Text.of("§b - Apprentice Source Circuits"))
        .tooltip(Text.of("§b - Mage Source Circuits"))
        .tooltip(Text.of("§b - Master Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 2 Source Circuits"))
    
    event.create("source_circuits_tier_3")
        .displayName("§aApprentice Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 15"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Circuits"))
        .tooltip(Text.of("§b - Novice Source Circuits"))
        .tooltip(Text.of("§b - Mage Source Circuits"))
        .tooltip(Text.of("§b - Master Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 3 Source Circuits"))
    
    event.create("source_circuits_tier_4")
        .displayName("§bMage Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 20"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Circuits"))
        .tooltip(Text.of("§b - Novice Source Circuits"))
        .tooltip(Text.of("§b - Apprentice Source Circuits"))
        .tooltip(Text.of("§b - Master Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 4 Source Circuits"))
    
    event.create("source_circuits_tier_5")
        .displayName("§dMaster Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 25"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Circuits"))
        .tooltip(Text.of("§b - Novice Source Circuits"))
        .tooltip(Text.of("§b - Apprentice Source Circuits"))
        .tooltip(Text.of("§b - Mage Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 5 Source Circuits"))
    
    event.create("source_circuits_tier_6")
        .displayName("§6Archmage Source Circuits")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Reduce the cost of all spells by 30"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Circuits"))
        .tooltip(Text.of("§b - Novice Source Circuits"))
        .tooltip(Text.of("§b - Apprentice Source Circuits"))
        .tooltip(Text.of("§b - Mage Source Circuits"))
        .tooltip(Text.of("§b - Master Source Circuits"))
        .tooltip(Text.of("§b - Archmage Source Circuits"))
        .tooltip(Text.of("Bone Slot"))
        .tooltip(Text.of("§8Tier 6 Source Circuits"))


    ///////////////////////////////////////
    /// Fortuitous Frequency Multiplier ///
    ///////////////////////////////////////

    event.create("fortiutous_frequency_multiplier_tier_1")
        .displayName("§8Starter Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Make critical hits with spells 5% more frequent"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Novice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Apprentice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Mage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Master Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Archmage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 1 Fortiutous Frequency Multiplier"))

    event.create("fortiutous_frequency_multiplier_tier_2")
        .displayName("§7Novice Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Make critical hits with spells 10% more frequent"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Apprentice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Mage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Master Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Archmage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 2 Fortiutous Frequency Multiplier"))

    event.create("fortiutous_frequency_multiplier_tier_3")
        .displayName("§aApprentice Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Make critical hits with spells 20% more frequent"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Novice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Mage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Master Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Archmage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 3 Fortiutous Frequency Multiplier"))

    event.create("fortiutous_frequency_multiplier_tier_4")
        .displayName("§bMage Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Make critical hits with spells 35% more frequent"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Novice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Apprentice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Master Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Archmage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 4 Fortiutous Frequency Multiplier"))

    event.create("fortiutous_frequency_multiplier_tier_5")
        .displayName("§dMaster Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7Make critical hits with spells 60% more frequent"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Novice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Apprentice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Mage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Archmage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 5 Fortiutous Frequency Multiplier"))

    event.create("fortiutous_frequency_multiplier_tier_6")
        .displayName("§6Archmage Fortiutous Frequency Multiplier")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7All Hits with spells are critical hits"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Novice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Apprentice Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Mage Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("§b - Master Fortiutous Frequency Multiplier"))
        .tooltip(Text.of("Eyes Slot"))
        .tooltip(Text.of("§8Tier 6 Fortiutous Frequency Multiplier"))


    ///////////////////
    /// Spell Focus ///
    ///////////////////

    event.create("spell_focus_tier_1")
        .displayName("§8Starter Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+1 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Novice Spell Focus"))
        .tooltip(Text.of("§b - Apprentice Spell Focus"))
        .tooltip(Text.of("§b - Mage Spell Focus"))
        .tooltip(Text.of("§b - Master Spell Focus"))
        .tooltip(Text.of("§b - Archmage Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 1 Spell Focus"))

    event.create("spell_focus_tier_2")
        .displayName("§7Novice Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+2 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Spell Focus"))
        .tooltip(Text.of("§b - Apprentice Spell Focus"))
        .tooltip(Text.of("§b - Mage Spell Focus"))
        .tooltip(Text.of("§b - Master Spell Focus"))
        .tooltip(Text.of("§b - Archmage Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 2 Spell Focus"))

    event.create("spell_focus_tier_3")
        .displayName("§aApprentice Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+4 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Spell Focus"))
        .tooltip(Text.of("§b - Novice Spell Focus"))
        .tooltip(Text.of("§b - Mage Spell Focus"))
        .tooltip(Text.of("§b - Master Spell Focus"))
        .tooltip(Text.of("§b - Archmage Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 3 Spell Focus"))

    event.create("spell_focus_tier_4")
        .displayName("§bMage Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+8 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Spell Focus"))
        .tooltip(Text.of("§b - Novice Spell Focus"))
        .tooltip(Text.of("§b - Apprentice Spell Focus"))
        .tooltip(Text.of("§b - Master Spell Focus"))
        .tooltip(Text.of("§b - Archmage Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 4 Spell Focus"))

    event.create("spell_focus_tier_5")
        .displayName("§dMaster Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+16 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Spell Focus"))
        .tooltip(Text.of("§b - Novice Spell Focus"))
        .tooltip(Text.of("§b - Apprentice Spell Focus"))
        .tooltip(Text.of("§b - Mage Spell Focus"))
        .tooltip(Text.of("§b - Archmage Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 5 Spell Focus"))

    event.create("spell_focus_tier_6")
        .displayName("§6Archmage Spell Focus")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+32 Spell Power"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Spell Focus"))
        .tooltip(Text.of("§b - Novice Spell Focus"))
        .tooltip(Text.of("§b - Apprentice Spell Focus"))
        .tooltip(Text.of("§b - Mage Spell Focus"))
        .tooltip(Text.of("§b - Master Spell Focus"))
        .tooltip(Text.of("Hand Slot"))
        .tooltip(Text.of("§8Tier 6 Spell Focus"))


    /////////////////////////////
    /// Auxillary Source Core ///
    /////////////////////////////

    event.create("auxillary_source_core_tier_1")
        .displayName("§8Starter Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+50% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Novice Auxillary Source Core"))
        .tooltip(Text.of("§b - Apprentice Auxillary Source Core"))
        .tooltip(Text.of("§b - Mage Auxillary Source Core"))
        .tooltip(Text.of("§b - Master Auxillary Source Core"))
        .tooltip(Text.of("§b - Archmage Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 1 Auxillary Source Core"))

    event.create("auxillary_source_core_tier_2")
        .displayName("§7Novice Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+100% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Auxillary Source Core"))
        .tooltip(Text.of("§b - Apprentice Auxillary Source Core"))
        .tooltip(Text.of("§b - Mage Auxillary Source Core"))
        .tooltip(Text.of("§b - Master Auxillary Source Core"))
        .tooltip(Text.of("§b - Archmage Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 2 Auxillary Source Core"))

    event.create("auxillary_source_core_tier_3")
        .displayName("§aApprentice Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+150% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Auxillary Source Core"))
        .tooltip(Text.of("§b - Novice Auxillary Source Core"))
        .tooltip(Text.of("§b - Mage Auxillary Source Core"))
        .tooltip(Text.of("§b - Master Auxillary Source Core"))
        .tooltip(Text.of("§b - Archmage Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 3 Auxillary Source Core"))

    event.create("auxillary_source_core_tier_4")
        .displayName("§bMage Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+200% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Auxillary Source Core"))
        .tooltip(Text.of("§b - Novice Auxillary Source Core"))
        .tooltip(Text.of("§b - Apprentice Auxillary Source Core"))
        .tooltip(Text.of("§b - Master Auxillary Source Core"))
        .tooltip(Text.of("§b - Archmage Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 4 Auxillary Source Core"))

    event.create("auxillary_source_core_tier_5")
        .displayName("§dMaster Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+250% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Auxillary Source Core"))
        .tooltip(Text.of("§b - Novice Auxillary Source Core"))
        .tooltip(Text.of("§b - Apprentice Auxillary Source Core"))
        .tooltip(Text.of("§b - Mage Auxillary Source Core"))
        .tooltip(Text.of("§b - Archmage Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 5 Auxillary Source Core"))

    event.create("auxillary_source_core_tier_6")
        .displayName("§6Archmage Auxillary Source Core")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+300% Source Regeneration"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Auxillary Source Core"))
        .tooltip(Text.of("§b - Novice Auxillary Source Core"))
        .tooltip(Text.of("§b - Apprentice Auxillary Source Core"))
        .tooltip(Text.of("§b - Mage Auxillary Source Core"))
        .tooltip(Text.of("§b - Master Auxillary Source Core"))
        .tooltip(Text.of("Heart Slot"))
        .tooltip(Text.of("§8Tier 6 Auxillary Source Core"))


    ////////////////////////
    /// Source Capacitor ///
    ////////////////////////

    event.create("source_capacitor_tier_1")
        .displayName("§8Starter Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+50% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Novice Source Capacitor"))
        .tooltip(Text.of("§b - Apprentice Source Capacitor"))
        .tooltip(Text.of("§b - Mage Source Capacitor"))
        .tooltip(Text.of("§b - Master Source Capacitor"))
        .tooltip(Text.of("§b - Archmage Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 1 Source Capacitor"))

    event.create("source_capacitor_tier_2")
        .displayName("§7Novice Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+100% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Capacitor"))
        .tooltip(Text.of("§b - Apprentice Source Capacitor"))
        .tooltip(Text.of("§b - Mage Source Capacitor"))
        .tooltip(Text.of("§b - Master Source Capacitor"))
        .tooltip(Text.of("§b - Archmage Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 2 Source Capacitor"))

    event.create("source_capacitor_tier_3")
        .displayName("§aApprentice Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+150% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Capacitor"))
        .tooltip(Text.of("§b - Novice Source Capacitor"))
        .tooltip(Text.of("§b - Mage Source Capacitor"))
        .tooltip(Text.of("§b - Master Source Capacitor"))
        .tooltip(Text.of("§b - Archmage Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 3 Source Capacitor"))

    event.create("source_capacitor_tier_4")
        .displayName("§bMage Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+200% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Capacitor"))
        .tooltip(Text.of("§b - Novice Source Capacitor"))
        .tooltip(Text.of("§b - Apprentice Source Capacitor"))
        .tooltip(Text.of("§b - Master Source Capacitor"))
        .tooltip(Text.of("§b - Archmage Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 4 Source Capacitor"))

    event.create("source_capacitor_tier_5")
        .displayName("§dMaster Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+250% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Capacitor"))
        .tooltip(Text.of("§b - Novice Source Capacitor"))
        .tooltip(Text.of("§b - Apprentice Source Capacitor"))
        .tooltip(Text.of("§b - Mage Source Capacitor"))
        .tooltip(Text.of("§b - Archmage Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 5 Source Capacitor"))

    event.create("source_capacitor_tier_6")
        .displayName("§6Archmage Source Capacitor")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7+300% Source Capacity"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Starter Source Capacitor"))
        .tooltip(Text.of("§b - Novice Source Capacitor"))
        .tooltip(Text.of("§b - Apprentice Source Capacitor"))
        .tooltip(Text.of("§b - Mage Source Capacitor"))
        .tooltip(Text.of("§b - Master Source Capacitor"))
        .tooltip(Text.of("Lower Organs Slot"))
        .tooltip(Text.of("§8Tier 6 Source Capacitor"))

    })
