
// Create Items
StartupEvents.registry('item', event => {

    event.create("tooltip_color_palette")
        .displayName("Tooltip Color Palette")
        .tooltip(Text.of("§0 | Black"))
        .tooltip(Text.of("§1 | Dark Blue"))
        .tooltip(Text.of("§2 | Dark Green"))
        .tooltip(Text.of("§3 | Dark Aqua"))
        .tooltip(Text.of("§4 | Dark Red"))
        .tooltip(Text.of("§5 | Dark Purple"))
        .tooltip(Text.of("§6 | Gold"))
        .tooltip(Text.of("§7 | Gray"))
        .tooltip(Text.of("§8 | Dark Gray"))
        .tooltip(Text.of("§9 | Blue"))
        .tooltip(Text.of("§a | Green"))
        .tooltip(Text.of("§b | Aqua"))
        .tooltip(Text.of("§c | Red"))
        .tooltip(Text.of("§d | Light Purple"))
        .tooltip(Text.of("§e | Yellow"))
        .tooltip(Text.of("§f | White"))


    //////////////////////
    /// Dermal Plating ///
    //////////////////////

    event.create("dermal_plating_gold")
        .displayName("§8Gold Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +3 Armor"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 1 Dermal Plating"))

    event.create("dermal_plating_iron")
        .displayName("§8Iron Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +4 Armor"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 2 Dermal Plating"))

    event.create("dermal_plating_diamond")
        .displayName("§bDiamond Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +5 Armor"))
        .tooltip(Text.of("§7 Gives +2 Armor Toughness"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Netherite Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 3 Dermal Plating"))

    event.create("dermal_plating_netherite")
        .displayName("§dNetherite Dermal Plating")
        .tooltip(Text.of(""))
        .tooltip(Text.of("§7 Gives +5 Armor"))
        .tooltip(Text.of("§7 Gives +3 Armor Toughness"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cMax Install: 4"))
        .tooltip(Text.of("§5Essence Cost: 5"))
        .tooltip(Text.of(""))
        .tooltip(Text.of("§cIncompatible with:"))
        .tooltip(Text.of("§b - Gold Dermal Plating"))
        .tooltip(Text.of("§b - Iron Dermal Plating"))
        .tooltip(Text.of("§b - Diamond Dermal Plating"))
        .tooltip(Text.of("§7Skin Slot"))
        .tooltip(Text.of("§8Tier 4 Dermal Plating"))

    })
